/*
COMANDO SELECT
SELEÇÃO,PROJEÇÃO E JUNÇÃO 
*/
SELECT NOW();
SELECT 'FELIPE MAFRA';
SELECT 'BANCO DE DADOS';

/*ALIAS DE COLUNAS*/
SELECT NOME, SEXO, EMAIL FROM CLIENTES;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTES;