# -*- coding: utf-8 -*-
"""Imersão Python-Aulas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x-FdK8Zlw3NV2nh2yqWKeo_4w5tMW6I4

Aula 02 - Importação
"""

import pandas as pd

df_principal = pd.read_excel("/[Arquivo Puro] Imersão Python - Tabela de ações.xlsx", sheet_name="Principal")
df_principal.head(10)

df_total_acoes = pd.read_excel("/[Arquivo Puro] Imersão Python - Tabela de ações.xlsx", sheet_name="Total_de_acoes")
df_total_acoes

df_ticker = pd.read_excel("/[Arquivo Puro] Imersão Python - Tabela de ações.xlsx", sheet_name="Ticker")
df_ticker