Algoritmo "teste_saida"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/03/2023
Var
   a:inteiro
   b:real
   c:caractere
   d:logico



// Seção de Declarações das variáveis 


Inicio
a<-32
b<-2.34567
c<-"bom dia"
d<-VERDADEIRO
  escreval(a)
  escreval(b)
  escreval(b:10)
  escreval(c)
  escreval(d)

Fimalgoritmo